# î‚¼, î­°, î‚º, î‚¸
# [î‚¶](fg:bg)
format = """
$directory\
$all\
$status\
$memory_usage\
[î‚¸](fg:prev_bg) \
$character"""

right_format = """
[\
$cmd_duration\
$nodejs\
$python\
$kubernetes\
$jobs\
$shlvl\
$time\
](bg:bg)"""

add_newline = false
palette = "default"

[palettes.default]
bg = "#424242"
# bg = "#525256"


[battery]
format = "[[î‚¾](bg:prev_bg fg:bg)$symbol$percentage]($style)"
[[battery.display]]
style = "bold red bg:bg"

[character]
disabled = true

[cmd_duration]
format = "[[î‚¾](bg:prev_bg fg:bg)ó±¦Ÿ $duration]($style)"
style = "yellow bg:bg"

[directory]
# style = "fg:#e3e5e5 bg:#769ff0"
style = "bold cyan bg:bg"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = "â€¦/"
use_os_path_sep = false
repo_root_style = "bold underline cyan bg:bg"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[gcloud]
disabled = true

[git_branch]
# symbol = "ï˜"
symbol = "ï¯™"
style = "fg:#12bd09 bg:#3C4563"
format = '[[î‚¸](fg:prev_bg bg:#394260)$symbol$branch]($style)'

[git_status]
style = "fg:#12bd09 bold bg:#394260"
format = '[($all_status$ahead_behind)]($style)'
ahead = 'ğŸ‡'
behind = 'ğŸ¢'
diverged = 'ó°™'
up_to_date = ""
conflicted = '[ó°˜•$count](yellow bold bg:bg)'
untracked = ''
modified = ''
staged = '[+$count](green bg:#394260)'
deleted = '[-$count](#B23333 bg:#394260)'
renamed = '[ó±€±$count](cyan bg:#394260)'
typechanged = "îš"
stashed = ""

[jobs]
symbol = "ï€“"

[kubernetes]
disabled = false
format = '[[î‚¾](bg:prev_bg fg:bg)$context]($style)'
detect_env_vars = ["KUBECONIFIG"]

[line_break]
disabled = true

[memory_usage]
disabled = false
symbol = "ğŸ’¥"
format = "$symbol[${ram}( | ${swap})]($style)"

[lua]
disabled = true
symbol = "ó°¢±"

[nodejs]
format = '[[î‚¾](bg:prev_bg fg:bg)${symbol}(${version})]($style)'

[package]
disabled = true

[python]
format = '[[î‚¾](bg:prev_bg fg:bg)${symbol}(${version})]($style)'
symbol = "îœ¼"
style = "bg:bg"

[shlvl]
disabled = false
format = '[[î‚¾](bg:prev_bg fg:bg)$symbol$shlvl]($style)'

[status]
disabled = false
format = "[[î‚¾](bg:prev_bg fg:bg)$symbol$status ]($style)"
style = "bold red bg:bg"

[sudo]
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# ïº
format = '[[î‚¾](bg:prev_bg fg:bg)$time]($style)'
style = "#ffecb3 bg:bg"
