# î‚¼, î­°, î‚º, î‚¸
# [î‚¶](fg:bg)
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status\
$memory_usage\
[î‚¸](fg:prev_bg) \
$character"""

right_format = """
[\
$jobs\
 \
$cmd_duration\
$shlvl\
$all\
$time\
](bg:bg)"""

add_newline = false
palette = "default"

[palettes.default]
bg = "#424242"
# bg = "#525256"


[aws]
# format ="[[î‚¾](bg:prev_bg fg:bg)$symbol($profile)( \\($region\\))( \\[$duration\\])]($style)"
format ="[[î‚¾](bg:prev_bg fg:bg)$symbol($profile)( \\[$duration\\])]($style)"
symbol = "ï‰°"
style = "bold #FFA500 bg:bg"

[battery]
format = "[[î‚¾](bg:prev_bg fg:bg)$symbol$percentage]($style)"
[[battery.display]]
style = "bold red bg:bg"

[character]
disabled = true

[cmd_duration]
format = "[[î‚¾](bg:prev_bg fg:bg)ó±¦Ÿ $duration]($style)"
style = "yellow bg:bg"
min_time = 10000

[gradle]
disabled = true

[directory]
# style = "fg:#e3e5e5 bg:#769ff0"
style = "bold cyan bg:bg"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = "â€¦/"
use_os_path_sep = false
repo_root_style = "bold underline cyan bg:bg"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[docker_context]
disabled = true


[gcloud]
disabled = true

[git_branch]
# symbol = "ï˜"
symbol = "î¬€ "
# symbol = "ï¯™"
style = "fg:#12bd09 bg:#3C4563"
format = '[[î‚¸](fg:prev_bg bg:#394260)$symbol$branch]($style)'
truncation_length = 15

[git_commit]
style = "green bold bg:#394260"
format = "[\\($hash$tag\\)]($style)"

[git_state]
style = "bold yellow bg:#394260"

[git_status]
style = "fg:#12bd09 bold bg:#394260"
format = '[($all_status$ahead_behind)]($style)'
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'ó°™'
up_to_date = ""
conflicted = '[ó°˜•$count](yellow bold bg:#394260)'
untracked = ''
modified = ''
staged = '[+$count](green bg:#394260)'
deleted = '[-$count](#B23333 bg:#394260)'
renamed = '[ó±€±$count](cyan bg:#394260)'
typechanged = "ó°™°"
stashed = ""

[java]
format = "[[î‚¾](bg:prev_bg fg:bg)$symbol($version)]($style)"
symbol = "îœ¸"
style = "#B07219 bg:bg"

[jobs]
# symbol = "ï€“"
format = "[$symbol$number]($style)"
# style = "bold blue"

[kubernetes]
disabled = false
format = '[[î‚¾](bg:prev_bg fg:bg)$context]($style)'
detect_env_vars = ["KUBECONIFIG"]

[line_break]
disabled = true

[memory_usage]
disabled = false
symbol = "ğŸ’¥"
format = "$symbol[${ram}( | ${swap})]($style)"

[lua]
disabled = true
symbol = "ó°¢±"

[nodejs]
format = '[[î‚¾](bg:prev_bg fg:bg)${symbol}(${version})]($style)'
style ="bold green bg:bg"

[package]
disabled = true

[python]
format = '[[î‚¾](bg:prev_bg fg:bg)${symbol}(${version})]($style)'
symbol = "îœ¼"
# style = "bg:bg"
style = "#ffdf76 bold bg:bg"

[rust]
format ="[[î‚¾](bg:prev_bg fg:bg)$symbol($version)]($style)"
style = "bold red bg:bg"

[shlvl]
disabled = false
format = '[[î‚¾](bg:prev_bg fg:bg)$symbol$shlvl]($style)'

[status]
disabled = false
format = "[[î‚¾](bg:prev_bg fg:bg)$symbol$status ]($style)"
style = "bold red bg:bg"

[sudo]
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# ïº
format = '[[î‚¾](bg:prev_bg fg:bg)$time]($style)'
style = "#ffecb3 bg:bg"
